-- entries表改用软删除(soft delete / tombstone)，不再物理删除行
--
-- 背景：washi-ledger前端为了防止"本机离线/登录失效期间攒的新记录被云端数据覆盖"
-- (跟旧App index.html的B-02同一类问题)，有一套按id把远端拉回来的数据跟本机现有
-- 数据合并的逻辑——远端GET结果里没有的本机id，会被当成"本机独有、还没同步过的
-- 新记录"，自动补推上云端。这套逻辑跟"物理删除"天生对不上：一旦某条记录被真的
-- DELETE掉，下次合并时远端GET自然也拉不到它，会被这套逻辑误判成"独有新记录"，
-- 反手又把刚删掉的记录重新upsert回去——2026-08-23前后端分家(Cloudflare Worker)
-- 回归测试删除功能时真实复现过这个问题。
--
-- 加一列deleted_at标记删除后：
-- 1) 正常查询(GET /entries)过滤掉deleted_at不为空的行，前端看到的效果跟真删除一样
-- 2) 就算合并逻辑还是把某条已标记删除的记录误判成"独有记录"又推了一次upsert，
--    upsert请求体里不包含deleted_at这个字段，PostgREST的upsert只会更新请求体里
--    出现的列，不会把这一列改回null，这行还是保持"已删除"，救不活
--
-- 用途：在 Supabase SQL Editor 里直接执行。
-- 幂等：可以安全重复执行(列已存在的话这条语句不会报错)。
--
-- 没做的事(留到以后真的需要时再加)：定期物理清理deleted_at很久以前的行——现在
-- 这些标记删除的行会一直留在表里，只是不出现在查询结果里，不影响功能，但表会
-- 越积越大。

alter table public.entries add column if not exists deleted_at timestamptz;
